site_name: AED Surubí
site_author: Chipaaco
nav:
  - Introducciȯn: index.md
  - Condicionales: 02-secuenciales-condicionales.md
  - Repetitivas: 03-repetitivas.md
  - Funciones y Procedimientos: 04-funciones-procedimientos.md
  - Secuencias de datos: 05-secuencias-datos.md
  - Subsecuencias: 06-subsecuencias.md
  - Registros: 07-registros.md
  - Archivos: 08-archivos.md
  - Procesos con Archivos: 09-procesos-archivos.md
  - Corte de Control: 10-corte-control.md
theme:
  name: material
  language: es
  features:
    - header.autohide
    - navigation.path
  palette: 

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    logo: material/file

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - toc:

      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
